# -*- coding: utf-8 -*-
"""Copy of Cats and Dogs CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVUFf0r_Sx8IXG9T6fk5D3xIKSDd84l7
"""

# connect to t4 gpu
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Input
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from google.colab import drive
drive.mount('/content/drive')

# Generate batches of tensor image data with real-time data augmentation.
datagen = ImageDataGenerator(rescale=1./255,
                                                     rotation_range=30,
                                                    horizontal_flip=True)

training_set=datagen.flow_from_directory('/content/drive/MyDrive/datafiles/SmallDataset/training_set',
                                        target_size=(64,64),
                                        batch_size=20,
                                        class_mode = 'binary')
test_set=datagen.flow_from_directory('/content/drive/MyDrive/datafiles/SmallDataset/test_set',
                                    target_size=(64,64),
                                    batch_size=20,
                                    class_mode = 'binary')
# class_mode='categorical' if you have more than 2 classses

model = Sequential()
model.add(Input((64,64,3)))
model.add(Conv2D(32,(3,3)))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(64, (3,3)))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(128, (3,3)))
model.add(MaxPooling2D(2,2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

model.fit(training_set, epochs=30, validation_data=test_set)

from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
import numpy as np

img = image.load_img('/content/drive/MyDrive/datafiles/SmallDataset/single_prediction/c4.jpg'
                    ,target_size = (64,64))
plt.figure(figsize=(1,1))
plt.imshow(img);
test_img = np.asarray(img)
print(test_img.shape)
# reshape to add 1 row
test_img = test_img.reshape(1,64,64,3)
print(test_img.shape)
model.predict(test_img)

from tensorflow.keras.models import save_model

save_model(model, 'mycatsdogs.h5')

img = image.load_img('/content/download.jpg'
                    ,target_size = (64,64))
plt.figure(figsize=(1,1))
plt.imshow(img);
test_img = np.asarray(img)
print(test_img.shape)
# reshape to add 1 row
test_img = test_img.reshape(1,64,64,3)
print(test_img.shape)
model.predict(test_img)

