# -*- coding: utf-8 -*-
"""LSTM model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Xb-UGgLeheGVy4C51oYnPKIC7ZdOs8x
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("ammarridho/drowsiness-cut")

print("Path to dataset files:", path)

cnn_full.build((None, 100, 100, 3))

from tensorflow.keras.models import Model

cnn_feature_extractor = Model(
    inputs=cnn_full.layers[0].input,
    outputs=cnn_full.layers[-2].output
)


for layer in cnn_feature_extractor.layers:
    layer.trainable = False

cnn_feature_extractor.summary()

def load_sequence_features_and_label(seq_path, cnn_classifier, cnn_feature_extractor):
    frames = sorted(os.listdir(seq_path))[:SEQ_LEN]
    images = []

    for frame in frames:
        img_path = os.path.join(seq_path, frame)
        img = cv2.imread(img_path)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = img / 255.0
        images.append(img)

    images = np.array(images)

    # One forward pass
    frame_probs = cnn_classifier.predict(images, verbose=0)
    features = cnn_feature_extractor.predict(images, verbose=0)

    # Majority vote label
    label = int(np.mean(frame_probs) > 0.5)

    return features, label

def build_sequence_dataset(seq_root, cnn_classifier, cnn_feature_extractor):
    X, y = [], []

    seq_folders = sorted(os.listdir(seq_root))

    for i, seq_folder in enumerate(seq_folders):
        seq_path = os.path.join(seq_root, seq_folder)

        if os.path.isdir(seq_path):
            features, label = load_sequence_features_and_label(
                seq_path,
                cnn_classifier,
                cnn_feature_extractor
            )

            X.append(features)
            y.append(label)

        if i % 50 == 0:
            print(f"Processed {i}/{len(seq_folders)} sequences")

    return np.array(X), np.array(y)

X_seq, y_seq = build_sequence_dataset(
   path+ "/test",
    cnn_classifier,
    cnn_feature_extractor
)

print(X_seq.shape)
print(y_seq.shape)

# Check label distribution
unique, counts = np.unique(y_seq, return_counts=True)
print(dict(zip(unique, counts)))

for i in [0, 1, 2]:
    print(f"Sequence {i}: label = {y_seq[i]}")

"""import numpy as np

np.save("X_seq_features.npy", X_seq)

np.save("y_seq_labels.npy", y_seq)

print("Sequence feature dataset saved")

from google.colab import files

files.download("X_seq_features.npy")

files.download("y_seq_labels.npy")

### if want to import those saved ones:

X_seq = np.load("X_seq_features.npy")

y_seq = np.load("y_seq_labels.npy")

np.save("cnn_pseudo_labels.npy", y_seq)

files.download("cnn_pseudo_labels.npy")
"""

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X_seq,
    y_seq,
    test_size=0.2,
    random_state=42,
    stratify=y_seq   # VERY IMPORTANT
)

print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weight_dict = dict(zip(classes, class_weights))
print(class_weight_dict)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input

lstm_model = Sequential([
    Input(shape=(30, 128)),
    LSTM(128),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

lstm_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

lstm_model.summary()

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True,
    verbose=1
)

history = lstm_model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=30,
    batch_size=8,
    class_weight=class_weight_dict,
    callbacks=[early_stop],
    verbose=1
)

y_val_prob = lstm_model.predict(X_val)
y_val_pred = (y_val_prob > 0.5).astype(int).ravel()

from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_val, y_val_pred)
print(cm)

print(classification_report(
    y_val,
    y_val_pred,
    target_names=["Drowsy", "Non-Drowsy"]
))

lstm_model.save("lstm_drowsiness_stage3.h5")
print("LSTM model saved")